In [1]:
#!#pip install numpy
!pip install pandas matplotlib seaborn scikit-learn xgboost
!pip install tensorflow

Requirement already satisfied: pandas in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: matplotlib in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (3.9.1)
Requirement already satisfied: seaborn in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (1.5.2)
Collecting xgboost
  Downloading xgboost-2.1.4-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading xgboost-2.1.4-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
    --------------------------------------- 1.6/124.9 MB 9.4 MB/s eta 0:00:14
   - -------------------------------------- 3.1/124.9 MB 8.8 MB/s eta 0:00:14
   - -------------------------------------- 4.5/124.9 MB 7.9 MB/s eta 0:00:16
   -- ------------------------------------- 6.3/124.9 MB 7.9 MB/s eta 0:00:16
   -- ------------------------------------- 7.9/124.9 MB 8.0 MB/s eta 0:00:15
   --- ------------------------------------ 9.4/124.9 MB 8.0 MB/s eta 0:00:15
   --- ------------------------------------ 11.0/124.9 MB 7.9 MB/s eta 0:00:15
   ---- ----------------------------------- 12.6/124.9 MB 7.9 MB/s eta 0:00:15
   ---- ----------------------------------- 14.4/124.9 MB 8.0 MB/s eta 0:00:14
   ----- ---------------------------------- 16.0/124.9 MB 8.1 MB/s eta 0:00:14
   ----- ---------------------------------- 17.8/124.9 MB 8.1 MB/s eta 0:00:14
   ------ --------------------------------- 19.4/124.9 MB 8.1 MB/s eta 0:00:14
   ------ --------------------------------- 21.0/124.9 MB 8.0 MB/s eta 0:00:13
   ------- -------------------------------- 22.5/124.9 MB 8.0 MB/s eta 0:00:13
   ------- -------------------------------- 24.4/124.9 MB 8.0 MB/s eta 0:00:13
   -------- ------------------------------- 26.2/124.9 MB 8.1 MB/s eta 0:00:13
   -------- ------------------------------- 27.5/124.9 MB 8.0 MB/s eta 0:00:13
   --------- ------------------------------ 29.1/124.9 MB 7.9 MB/s eta 0:00:13
   --------- ------------------------------ 30.7/124.9 MB 7.9 MB/s eta 0:00:12
   ---------- ----------------------------- 32.2/124.9 MB 7.9 MB/s eta 0:00:12
   ---------- ----------------------------- 33.8/124.9 MB 7.9 MB/s eta 0:00:12
   ----------- ---------------------------- 35.7/124.9 MB 7.9 MB/s eta 0:00:12
   ------------ --------------------------- 37.5/124.9 MB 8.0 MB/s eta 0:00:11
   ------------ --------------------------- 39.3/124.9 MB 8.0 MB/s eta 0:00:11
   ------------- -------------------------- 40.9/124.9 MB 8.0 MB/s eta 0:00:11
   ------------- -------------------------- 43.0/124.9 MB 8.1 MB/s eta 0:00:11
   -------------- ------------------------- 44.6/124.9 MB 8.1 MB/s eta 0:00:10
   -------------- ------------------------- 45.9/124.9 MB 8.0 MB/s eta 0:00:10
   --------------- ------------------------ 47.2/124.9 MB 8.0 MB/s eta 0:00:10
   --------------- ------------------------ 48.5/124.9 MB 7.9 MB/s eta 0:00:10
   --------------- ------------------------ 49.8/124.9 MB 7.8 MB/s eta 0:00:10
   ---------------- ----------------------- 51.1/124.9 MB 7.8 MB/s eta 0:00:10
   ---------------- ----------------------- 52.7/124.9 MB 7.8 MB/s eta 0:00:10
   ----------------- ---------------------- 54.3/124.9 MB 7.8 MB/s eta 0:00:10
   ----------------- ---------------------- 55.8/124.9 MB 7.8 MB/s eta 0:00:09
   ------------------ --------------------- 57.7/124.9 MB 7.8 MB/s eta 0:00:09
   ------------------ --------------------- 58.5/124.9 MB 7.7 MB/s eta 0:00:09
   ------------------- -------------------- 59.8/124.9 MB 7.6 MB/s eta 0:00:09
   ------------------- -------------------- 61.1/124.9 MB 7.6 MB/s eta 0:00:09
   ------------------- -------------------- 62.1/124.9 MB 7.6 MB/s eta 0:00:09
   -------------------- ------------------- 63.7/124.9 MB 7.5 MB/s eta 0:00:09
   -------------------- ------------------- 64.7/124.9 MB 7.5 MB/s eta 0:00:09
   --------------------- ------------------ 66.3/124.9 MB 7.5 MB/s eta 0:00:08
   --------------------- ------------------ 68.2/124.9 MB 7.5 MB/s eta 0:00:08
   ---------------------- ----------------- 69.5/124.9 MB 7.5 MB/s eta 0:00:08
   ---------------------- ----------------- 71.3/124.9 MB 7.5 MB/s eta 0:00:08
   ----------------------- ---------------- 73.1/124.9 MB 7.6 MB/s eta 0:00:07
   ----------------------- ---------------- 74.7/124.9 MB 7.6 MB/s eta 0:00:07
   ------------------------ --------------- 76.3/124.9 MB 7.5 MB/s eta 0:00:07
   ------------------------ --------------- 77.6/124.9 MB 7.5 MB/s eta 0:00:07
   ------------------------- -------------- 79.2/124.9 MB 7.5 MB/s eta 0:00:07
   ------------------------- -------------- 80.2/124.9 MB 7.5 MB/s eta 0:00:06
   ------------------------- -------------- 81.0/124.9 MB 7.4 MB/s eta 0:00:06
   -------------------------- ------------- 82.1/124.9 MB 7.4 MB/s eta 0:00:06
   -------------------------- ------------- 83.1/124.9 MB 7.4 MB/s eta 0:00:06
   -------------------------- ------------- 84.1/124.9 MB 7.3 MB/s eta 0:00:06
   --------------------------- ------------ 85.5/124.9 MB 7.3 MB/s eta 0:00:06
   --------------------------- ------------ 86.5/124.9 MB 7.2 MB/s eta 0:00:06
   --------------------------- ------------ 87.3/124.9 MB 7.2 MB/s eta 0:00:06
   ---------------------------- ----------- 88.1/124.9 MB 7.1 MB/s eta 0:00:06
   ---------------------------- ----------- 89.1/124.9 MB 7.1 MB/s eta 0:00:06
   ---------------------------- ----------- 89.4/124.9 MB 7.1 MB/s eta 0:00:06
   ---------------------------- ----------- 90.2/124.9 MB 6.9 MB/s eta 0:00:06
   ----------------------------- ---------- 91.0/124.9 MB 6.9 MB/s eta 0:00:05
   ----------------------------- ---------- 92.0/124.9 MB 6.8 MB/s eta 0:00:05
   ----------------------------- ---------- 92.8/124.9 MB 6.8 MB/s eta 0:00:05
   ------------------------------ --------- 93.8/124.9 MB 6.8 MB/s eta 0:00:05
   ------------------------------ --------- 95.2/124.9 MB 6.8 MB/s eta 0:00:05
   ------------------------------ --------- 96.2/124.9 MB 6.8 MB/s eta 0:00:05
   ------------------------------- -------- 97.8/124.9 MB 6.7 MB/s eta 0:00:05
   ------------------------------- -------- 98.8/124.9 MB 6.7 MB/s eta 0:00:04
   ------------------------------- -------- 99.9/124.9 MB 6.7 MB/s eta 0:00:04
   -------------------------------- ------- 101.2/124.9 MB 6.7 MB/s eta 0:00:04
   -------------------------------- ------- 102.5/124.9 MB 6.7 MB/s eta 0:00:04
   --------------------------------- ------ 103.8/124.9 MB 6.7 MB/s eta 0:00:04
   --------------------------------- ------ 104.9/124.9 MB 6.7 MB/s eta 0:00:04
   --------------------------------- ------ 105.1/124.9 MB 6.6 MB/s eta 0:00:03
   --------------------------------- ------ 105.4/124.9 MB 6.6 MB/s eta 0:00:03
   --------------------------------- ------ 105.9/124.9 MB 6.5 MB/s eta 0:00:03
   ---------------------------------- ----- 106.7/124.9 MB 6.4 MB/s eta 0:00:03
   ---------------------------------- ----- 107.5/124.9 MB 6.4 MB/s eta 0:00:03
   ---------------------------------- ----- 108.3/124.9 MB 6.4 MB/s eta 0:00:03
   ---------------------------------- ----- 109.1/124.9 MB 6.3 MB/s eta 0:00:03
   ----------------------------------- ---- 109.8/124.9 MB 6.3 MB/s eta 0:00:03
   ----------------------------------- ---- 110.9/124.9 MB 6.3 MB/s eta 0:00:03
   ----------------------------------- ---- 111.9/124.9 MB 6.3 MB/s eta 0:00:03
   ------------------------------------ --- 113.2/124.9 MB 6.3 MB/s eta 0:00:02
   ------------------------------------ --- 114.6/124.9 MB 6.3 MB/s eta 0:00:02
   ------------------------------------- -- 115.9/124.9 MB 6.3 MB/s eta 0:00:02
   ------------------------------------- -- 117.4/124.9 MB 6.3 MB/s eta 0:00:02
   -------------------------------------- - 119.0/124.9 MB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 120.1/124.9 MB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 121.6/124.9 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------  122.9/124.9 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------  124.3/124.9 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------  124.8/124.9 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 124.9/124.9 MB 6.3 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-2.1.4
Requirement already satisfied: tensorflow in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (2.17.0)
Requirement already satisfied: tensorflow-intel==2.17.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.17.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.3.0)
Requirement already satisfied: packaging in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (4.25.4)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (70.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.66.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.17.1)
Requirement already satisfied: keras>=3.2.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.5.0)
Requirement already satisfied: numpy<2.0.0,>=1.26.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.17.0->tensorflow) (0.43.0)
Requirement already satisfied: rich in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (13.8.0)
Requirement already satisfied: namex in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2024.6.2)
Requirement already satisfied: markdown>=2.6.8 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (3.0.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\aniru\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.1.2)

IMPORTING NECESSARY LIBRARY

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn import metrics
from sklearn.svm import SVC
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import mean_absolute_error as mae

import warnings
warnings.filterwarnings('ignore')

dfSET LOADING

In [3]:
df = pd.read_csv('/home/infinity/Documents/IP/retail_store_inventory.csv')
display(df.head())
display(df.tail())

FileNotFoundError: [Errno 2] No such file or directory: '/home/infinity/Documents/IP/retail_store_inventory.csv'

SHAPE

In [ ]:
df.shape

(73100, 15)

DESCRIPTION

In [ ]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

INFO

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

FEATURE ENGINEERING

DERIVED ATTRIBUTES

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df.head(1000)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,2022,1,1
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,2022,1,1
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,2022,1,1
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2022-01-10,S005,P0016,Groceries,East,407,103,90,107.56,60.15,15,Sunny,1,64.52,Winter,2022,1,10
996,2022-01-10,S005,P0017,Furniture,East,308,266,164,259.60,31.07,20,Rainy,1,30.57,Summer,2022,1,10
997,2022-01-10,S005,P0018,Furniture,South,331,235,49,234.25,22.58,20,Cloudy,1,27.56,Summer,2022,1,10
998,2022-01-10,S005,P0019,Electronics,East,481,154,169,169.61,85.04,5,Cloudy,0,82.62,Autumn,2022,1,10
999,2022-01-10,S005,P0020,Toys,West,372,176,182,183.29,15.56,0,Sunny,1,19.15,Summer,2022,1,10

In [ ]:
#Deleting the Date column
df.drop('Date', axis=1, inplace=True)
df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day
0,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1
1,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,2022,1,1
2,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,2022,1,1
3,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,2022,1,1
4,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,2022,1,1

CYCLICAL ENCODING

In [ ]:
df['M1'] = np.sin(df['Month'] * (2 * np.pi / 12))
df['M2'] = np.cos(df['Month'] * (2 * np.pi / 12))
df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,M1,M2
0,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1,0.5,0.866025
1,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,2022,1,1,0.5,0.866025
2,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,2022,1,1,0.5,0.866025
3,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,2022,1,1,0.5,0.866025
4,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,2022,1,1,0.5,0.866025

VALUES ENCODING

STOCKOUT TIME CALCULATION

In [ ]:
# If historical data is not available, use a user-defined forecast growth rate from external research or expert opinions.
# For instance, let's assume industry research suggests a 3% monthly growth rate (0.03)
forecast_growth = 0.03
def calculate_stockout_time(row, forecast_growth=0):
    """
    Calculate the estimated stockout time in days.
    
    The adjusted demand rate factors in forecast growth:
        adjusted_demand = Units Sold * (1 + forecast_growth)
    
    Stockout time is then:
        Stockout Time = Inventory Level / adjusted_demand
    """
    
    # Calculate adjusted demand rate
    adjusted_demand = row["Units Sold"] * (1 + forecast_growth)
    # Avoid division by zero
    if adjusted_demand == 0:
        adjusted_demand+=1
    return row["Inventory Level"] / adjusted_demand

# Apply the calculation across the DataFrame
df["Stockout Time (days)"] = df.apply(lambda row: calculate_stockout_time(row, forecast_growth), axis=1)

In [ ]:
df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,M1,M2,Stockout Time (days)
0,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1,0.5,0.866025,1.765920
1,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,2022,1,1,0.5,0.866025,1.320388
2,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,2022,1,1,0.5,0.866025,1.523525
3,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,2022,1,1,0.5,0.866025,7.464587
4,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,2022,1,1,0.5,0.866025,11.511789

In [ ]:
data = df.copy()

LABEL ENCODING

In [ ]:
# List of categorical columns for label encoding:
categorical_columns = ["Store ID", "Product ID", "Category", "Region", 
                       "Weather Condition", "Seasonality"]

# Initialize a LabelEncoder
le = LabelEncoder()

# Apply label encoding to each categorical column:
for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,M1,M2,Stockout Time (days)
0,0,0,3,1,231,127,55,135.47,33.50,20,1,0,29.69,0,2022,1,1,0.5,0.866025,1.765920
1,0,1,4,2,204,150,66,144.04,63.01,20,3,0,66.16,0,2022,1,1,0.5,0.866025,1.320388
2,0,2,4,3,102,65,51,74.02,27.99,10,3,1,31.32,2,2022,1,1,0.5,0.866025,1.523525
3,0,3,4,1,469,61,164,62.18,32.72,10,0,1,34.74,0,2022,1,1,0.5,0.866025,7.464587
4,0,4,1,0,166,14,135,9.26,73.64,0,3,0,68.95,2,2022,1,1,0.5,0.866025,11.511789

NORMALIZATION

In [ ]:
numeric_columns = ["Inventory Level", "Units Sold", "Units Ordered", "Demand Forecast", 
                   "Price", "Discount", "Competitor Pricing"]

# Initialize the StandardScaler for normalization (z-score normalization)
scaler = MinMaxScaler(feature_range=(0,1))

# Fit and transform the numeric columns
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])
df.head()

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,M1,M2,Stockout Time (days)
0,0,0,3,1,0.402222,0.254509,0.194444,0.275211,0.261111,1.0,1,0,0.246822,0,2022,1,1,0.5,0.866025,1.765920
1,0,1,4,2,0.342222,0.300601,0.255556,0.291425,0.589000,1.0,3,0,0.611851,0,2022,1,1,0.5,0.866025,1.320388
2,0,2,4,3,0.115556,0.130261,0.172222,0.158947,0.199889,0.5,3,1,0.263137,2,2022,1,1,0.5,0.866025,1.523525
3,0,3,4,1,0.931111,0.122244,0.800000,0.136546,0.252444,0.5,0,1,0.297368,0,2022,1,1,0.5,0.866025,7.464587
4,0,4,1,0,0.257778,0.028056,0.638889,0.036421,0.707111,0.0,3,0,0.639776,2,2022,1,1,0.5,0.866025,11.511789

*MODEL TRAINING*

SPLITING TRAINING AND VALIDATION

In [ ]:
features = df.drop(['Stockout Time (days)'], axis=1)
target = df['Stockout Time (days)'].values


X_train, X_val, Y_train, Y_val = train_test_split(features, target,
                                                  test_size = 0.05,
                                                  random_state=22)
X_train.shape, X_val.shape

((69445, 19), (3655, 19))

MODEL USED LINEAR REGRESSION & XGB

In [ ]:
models = [LinearRegression(), XGBRegressor()]
pred =[]

for i in range(2):
    models[i].fit(X_train, Y_train)

    print(f'{models[i]} : ')

    train_preds = models[i].predict(X_train)
    print('Training Error : ', mae(Y_train, train_preds))

    val_preds = models[i].predict(X_val)
    pred.append(val_preds)
    print('Validation Error : ', mae(Y_val, val_preds))
    print()
    
print(max(pred[1]))

LinearRegression() :
Training Error :  8.444769244617309
Validation Error :  8.765281052721404

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...) :
Training Error :  0.0693521232419604
Validation Error :  0.10382393638212696

476.3888

In [ ]:

scaled_data =df.copy()

# Create time windows
def create_sequences(data, time_steps=180):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:i+time_steps, :-1])  # All features except target
        y.append(data[i+time_steps: -1])    # Target feature
    return np.array(X), np.array(y)

time_steps =180
X, y = create_sequences(scaled_data)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

InvalidIndexError: (slice(0, 180, None), slice(None, -1, None))

In [ ]:

# Create LSTM sequences
# Split into train and test
split = int(len(X) * 0.8)
X_train, X_test, y_train, y_test = X[:split], X[split:], y[:split], y[split:]
# Define LSTM model
lstm_model = Sequential([
    LSTM(50, return_sequences=False, input_shape=(time_steps, X.shape[2])),
    Dense(10, activation='relu'),
    Dense(1)
])

lstm_model.compile(optimizer='adam', loss='mse')
lstm_model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Extract LSTM features for XGBoost
lstm_features = lstm_model.predict(X)
train_features = lstm_features[:split]
test_features = lstm_features[split:]

KeyError: (10, 0)